//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessRules.POC.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    public sealed partial class RuleReferenceValue : global::System.Configuration.ApplicationSettingsBase {
        
        private static RuleReferenceValue defaultInstance = ((RuleReferenceValue)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new RuleReferenceValue())));
        
        public static RuleReferenceValue Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E,1,2")]
        public string AllowedLARSNotionalNVQLevelv2 {
            get {
                return ((string)(this["AllowedLARSNotionalNVQLevelv2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2016-08-01")]
        public string ApprencticeProgAllowedStartDate {
            get {
                return ((string)(this["ApprencticeProgAllowedStartDate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2, 3, 20, 21, 2, 23, 25")]
        public string ApprenticeProgTypes {
            get {
                return ((string)(this["ApprenticeProgTypes"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10,11,12, 98")]
        public string DD28Criteria2LearnerEmplStatusEmpStats {
            get {
                return ((string)(this["DD28Criteria2LearnerEmplStatusEmpStats"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BSI")]
        public string DD28Criteria2EmpStatusMonitoringESMType {
            get {
                return ((string)(this["DD28Criteria2EmpStatusMonitoringESMType"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1,2")]
        public string DD28Criteria2EmpStatusMonitoringESMCodes {
            get {
                return ((string)(this["DD28Criteria2EmpStatusMonitoringESMCodes"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11,12")]
        public string DD28Criteria1EMPStats {
            get {
                return ((string)(this["DD28Criteria1EMPStats"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BSI")]
        public string DD28Criteria1EMPType {
            get {
                return ((string)(this["DD28Criteria1EMPType"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3,4")]
        public string DD28Criteria1ESMCodes {
            get {
                return ((string)(this["DD28Criteria1ESMCodes"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string DD28Criteria3EMPStats {
            get {
                return ((string)(this["DD28Criteria3EMPStats"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EII")]
        public string DD28Criteria3ESMTypePart1 {
            get {
                return ((string)(this["DD28Criteria3ESMTypePart1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string DD28Criteria3ESMCodesPart1 {
            get {
                return ((string)(this["DD28Criteria3ESMCodesPart1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BSI")]
        public string DD28Criteria3ESMTypePart2 {
            get {
                return ((string)(this["DD28Criteria3ESMTypePart2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3,4")]
        public string DD28Criteria3ESMCodesPart2 {
            get {
                return ((string)(this["DD28Criteria3ESMCodesPart2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public string DD29LearningDeliveryProgType {
            get {
                return ((string)(this["DD29LearningDeliveryProgType"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2,4")]
        public string DD29LARSCategoryRef {
            get {
                return ((string)(this["DD29LARSCategoryRef"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LDM")]
        public string LearnDelFam66OlassFamType {
            get {
                return ((string)(this["LearnDelFam66OlassFamType"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("034")]
        public string LearnDelFam66OlassFamCode {
            get {
                return ((string)(this["LearnDelFam66OlassFamCode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LDM")]
        public string LearnDelFam66RotlFamType {
            get {
                return ((string)(this["LearnDelFam66RotlFamType"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("328")]
        public string LearnDelFam66RotlFamCode {
            get {
                return ((string)(this["LearnDelFam66RotlFamCode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RES")]
        public string LearnDelFam66RestartFamType {
            get {
                return ((string)(this["LearnDelFam66RestartFamType"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LDM")]
        public string LearnDelFam66SteelIndRedTrainingFamType {
            get {
                return ((string)(this["LearnDelFam66SteelIndRedTrainingFamType"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("347")]
        public string LearnDelFam66SteelIndRedTrainingFamCode {
            get {
                return ((string)(this["LearnDelFam66SteelIndRedTrainingFamCode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string LearnDelFam66RestartFamCode {
            get {
                return ((string)(this["LearnDelFam66RestartFamCode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LDM")]
        public string DD21AllowedFamType {
            get {
                return ((string)(this["DD21AllowedFamType"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("318")]
        public string DD21FamCodeShouldNotBe {
            get {
                return ((string)(this["DD21FamCodeShouldNotBe"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11,12")]
        public string DD21AllowedEmpStats {
            get {
                return ((string)(this["DD21AllowedEmpStats"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BSI")]
        public string DD21EmpTypePart1 {
            get {
                return ((string)(this["DD21EmpTypePart1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public string DD21EmpCodePart1 {
            get {
                return ((string)(this["DD21EmpCodePart1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BSI")]
        public string DD21EmpTypePart2 {
            get {
                return ((string)(this["DD21EmpTypePart2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public string DD21EmpCodePart2 {
            get {
                return ((string)(this["DD21EmpCodePart2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2017-08-01")]
        public string AcademicYearStart {
            get {
                return ((string)(this["AcademicYearStart"]));
            }
        }
    }
}
